In [3]:
import numpy as np
#tạo list
l = list(range(1,4))
#tạo ndarray
data = np.array(l)
print(data)
print(data[0])
print(data[1])

[1 2 3]
1
2


In [5]:
import numpy as np
list1D = [1,2,3]
data = np.array(list1D)
print(data)
print(data.shape)

[1 2 3]
(3,)


In [6]:
import numpy as np
l = list(range(1,4))
data = np.array(l)
print(data)
data[0]=8
print(data)

[1 2 3]
[8 2 3]


In [7]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
import numpy as np
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
import numpy as np
arr=np.full((2,3),999)
print(arr)

[[999 999 999]
 [999 999 999]]


In [10]:
import numpy as np
arr1=np.arange(5)
print(arr1)
arr2=np.arange(0,5,2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


In [11]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
import numpy as np
arr=np.random.random((3,4))
print(arr)

[[0.26212254 0.34944768 0.60380968 0.1327551 ]
 [0.5690251  0.38942286 0.59282324 0.75264666]
 [0.76732637 0.93920078 0.50728566 0.9657997 ]]


In [15]:
import numpy as np
arr=np.arange(5)
print(arr)
condition = arr < 3
out = np.where(condition,arr,arr*2)
print(condition)
print(out)

[0 1 2 3 4]
[ True  True  True False False]
[0 1 2 6 8]


In [16]:
import numpy as np
arr=np.array([[1,2],[3,4]])
out=arr.flatten()
print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


In [18]:
import numpy as np
l=[[1,2,3],
   [4,5,6]]
data=np.array(l)
print('data\n', data)
print('data shape\n', data.shape)
data_rs=np.reshape(data,(3,2))
print('data_rs\n', data_rs)
print('data_rs\n', data_rs.shape)

data
 [[1 2 3]
 [4 5 6]]
data shape
 (2, 3)
data_rs
 [[1 2]
 [3 4]
 [5 6]]
data_rs
 (3, 2)


In [19]:
import numpy as np
a_array=np.array([[1,2,3],
                  [5,6,7]])
b_array=a_array[:,1:3]
print(a_array)
print(b_array)

[[1 2 3]
 [5 6 7]]
[[2 3]
 [6 7]]


In [20]:
import numpy as np
a_array=np.array([[1,2,3],
                  [5,6,7]])
print('a_array\n', a_array)
b_array=a_array[:,1:3]
print('b_array\n',b_array)
print('before changing\n',a_array[0,1])
b_array[0,0]=99
print('appter changing\n',a_array[0,1])

a_array
 [[1 2 3]
 [5 6 7]]
b_array
 [[2 3]
 [6 7]]
before changing
 2
appter changing
 99


In [24]:
import numpy as np
arr=np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])
row_m1=arr[1,:]
row_m2=arr[1:2,:]
print(row_m1,row_m1.shape)
print(row_m1,row_m2.shape)

[5 6 7] (3,)
[5 6 7] (1, 3)


In [25]:
import numpy as np
arr=np.array([[1,2,3],
              [5,6,7],
              [9,10,11]])
col_m1=arr[:,1]
col_m2=arr[:,1:2]
print(col_m1,col_m1.shape)
print(col_m2,col_m2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [26]:
import numpy as np
x=np.array([5,6,7])
y=np.array([8,9,10])
print('data x \n',x)
print('data y \n',y)
print('method 1 \n',x-y)
print('method 2 \n',np.subtract(x,y))

data x 
 [5 6 7]
data y 
 [ 8  9 10]
method 1 
 [-3 -3 -3]
method 2 
 [-3 -3 -3]


In [27]:
import numpy as np
x=np.array([5,6,7])
y=np.array([8,9,10])
print('data x \n',x)
print('data y \n',y)
print('method 1 \n',x*y)
print('method 2 \n',np.multiply(x,y))

data x 
 [5 6 7]
data y 
 [ 8  9 10]
method 1 
 [40 54 70]
method 2 
 [40 54 70]


In [28]:
import numpy as np
x=np.array([5,6,7])
print('data x \n',x)
print('sqrt \n',np.sqrt(x))

data x 
 [5 6 7]
sqrt 
 [2.23606798 2.44948974 2.64575131]


In [29]:
import numpy as np
x=np.array([5,6])
y=np.array([8,9])
print('method 1 \n',x.dot(y))
print('method 2 \n',np.dot(x,y))

method 1 
 94
method 2 
 94


In [32]:
import numpy as np
x=np.array([[1,2],
           [3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [33]:
import numpy as np
x=np.array([5,6,7])
print('data max \n',x.max())
print('data min \n',x.min())

data max 
 7
data min 
 5


In [35]:
import numpy as np
x=np.array([[1,2,3],
            [4,5,6],
             [7,8,9]])
v=np.array([1,0,1])
y=x+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
